"""Builds outputs/07_RESEARCH_REPORT.md.  All numbers are read from the results files; qualitative statements were written after
inspecting those results and are conditional on the deterministic pipeline (no random components) being rerun on the same data."""
import os
import numpy as np, pandas as pd

def write_report(A, main, m4, rob, T3, T9, T10, diag, RES, OUT):
    def g(model, key, term, col="coef", df=main):
        return df[(df.model == model) & (df.outcome_key == key) & (df.term == term)][col].iloc[0]
    def cp(model, key, term, d=1, df=main):
        c, p = g(model, key, term, "coef", df), g(model, key, term, "p", df)
        return f"{c:.{d}f} (p={p:.3f})"
    def rb(cid, model, key, term, d=1):
        x = rob[(rob.check_id == cid) & (rob.model == model) & (rob.outcome_key == key) & (rob.term == term)]
        return f"{x.coef.iloc[0]:.{d}f} (p={x.p.iloc[0]:.3f})" if len(x) else "n/a"
    nM, nK = int((A.country == "MAR").sum()), int((A.country == "KOR").sum())
    ratio = A.sales_t / A.sales_t3
    heapM = int(((A.country == "MAR") & ((A.sales_t3 / A.sales_t).round(4) == 0.9)).sum()); vM = int(((A.country == "MAR") & ratio.notna()).sum())
    decM = 100 * (ratio[(A.country == "MAR")].dropna() < 1).mean(); decK = 100 * (ratio[(A.country == "KOR")].dropna() < 1).mean()
    badK = int(((A.country == "KOR") & ((ratio > 5) | (ratio < 0.2))).sum())
    cnt = T10.Verdict.str.split(":").str[0].value_counts().to_dict()
    ns = main[main.term == "const"].groupby(["outcome_key", "model"]).n.first().unstack()
    nrange = lambda m: f"{int(ns[m].min())}-{int(ns[m].max())}"
    dg = diag["Heterogeneity_T3"]
    sig_het = dg[(dg.wald_p < .05)][["group", "outcome_key", "sample"]].values.tolist()
    firth = diag["Firth_D4"]; f_ = firth[(firth.outcome_key == "D4_co2") & (firth["sample"] == "MAR") & (firth.regressor == "proc_innov")].iloc[0]
    vifmax = diag["VIF"].VIF.max()
    miss = diag["Missing_tests"]
    t9 = T9.set_index(["Outcome", "Regressor"])
    md = f"""# Innovation, Digitalization and Inclusive Firm Growth: Comparative Firm-Level Evidence from Morocco (WBES 2023) and South Korea (WBES 2024)

*Working research report generated by the reproducible pipeline (`python run_all.py`). Provisional title as proposed in the brief.*

## Abstract
Using World Bank Enterprise Surveys for Morocco 2023 (N = {nM}) and South Korea 2024 (N = {nK}), we test whether an integrated, multidimensional model of inclusive firm growth drawing on Phan (2026), Sime & Tadesse (2025) and Adewumi & Zhang (2026) is supported by the data. **It is only partly supported.** Economic growth (D1) and employment growth (D2) are measurable and comparable (harmonisable); social inclusion (D3) can be observed only as workforce *composition* at one date (female share; low-skilled share of production workers), not as inclusive employment *growth*; environmental sustainability (D4) is limited to two practice items (energy-management adoption, CO2 monitoring) because the Green Economy items used in the source articles are absent from both files. A composite index is not defensible (Cronbach alpha {diag_val(OUT,'alpha')}, KMO {diag_val(OUT,'kmo')}), so we estimate separate models. Product innovation, process innovation and a website proxy for digitalization are treated as **explanatory variables**. Across 42 country-by-outcome-by-regressor associations, {cnt.get('Robust',0)} are robust to our checks, {cnt.get('Fragile',0)} are fragile, {cnt.get('Unreliable',0)} is unreliable (sparse cell) and {cnt.get('Null/imprecise',0)} are null or imprecise; after Holm adjustment very few remain. The findings are conditional associations from cross-sectional data and carry no causal interpretation.

## 1. Contribution and positioning
None of the three source articles measures inclusive growth, builds a multidimensional index or studies Morocco and Korea together (see `01_ARTICLE_COMPARISON.md`). Our contribution is (i) a measurement audit showing which inclusive-growth dimensions the 2023/2024 WBES can support, (ii) harmonised comparative estimates for two contrasting economies, and (iii) an explicit account of what cannot be concluded. Phan (2026) supplies the product/process-innovation items (h1, h5) and the green-practice motivation; Sime & Tadesse (2025) the labour-market segmentation and the sales-per-worker productivity concept; Adewumi & Zhang (2026) the three-year sales-growth definition and the human-capital moderation argument.

## 2. Data and measurement
* **Data.** `Morocco-2023-full-data.dta` ({nM} firms, 354 variables) and `Korea-Republic-2024-full-data.dta` ({nK} firms, 339 variables); read-only copies in `data/raw/`. The Korea file is not valid UTF-8 and was read as latin1. Dictionaries and missing-data reports: `02_*.xlsx`.
* **Special codes** (-9 DK, -8 refused, -7 not applicable/not in business) are never treated as zero. Many labour items are routed to random half-samples (`l3a/l3b/l5a/l5b` vs `l5`; `l9b` vs `l9b1`) - structural missingness handled by combining the two routes (identity checks: `l3a+l3b = l1` and `l4a1+l4a2+l4b = l3a` hold in all comparable cases).
* **Crosswalk** (`03_VARIABLE_CROSSWALK.xlsx`): identical names were never assumed to be identical constructs; e.g. Phan's `b3` (large-owner share) is **not** the file's `b3a`, and Phan's `k8` corresponds to `k82`.
* **Indicators** (`04_INCLUSIVE_GROWTH_MEASUREMENT.xlsx`): D1 annualised log sales growth and productivity growth (= sales growth - employment growth); D2 annualised log growth of permanent full-time employment; D3 female share and low-skilled share of production workers; D4 `ge8d`, `ge7` (binary). Growth outcomes are winsorised at the 1st/99th percentile within country.
* **Explanatory variables:** product innovation (h1), process innovation (h5) - class A; website (c22b) - digitalization *proxy* (class C): no item on ICT adoption, software, automation or e-commerce exists.
* **Windows differ:** the last fiscal year closes in 2022 for ~90% of Moroccan firms (3-year window FY2019-FY2022) and in 2023 for ~98% of Korean firms (FY2020-FY2023); both windows include the COVID-19 period but at different phases. Growth is nominal; no deflator exists in the data and none was invented (see Section 6 for why slopes are unaffected by a common country deflator when growth is in logs).

### 2.1 Data-quality findings that qualify the D1 results
1. **Heaping in Moroccan sales.** {heapM} of {vM} Moroccan firms with valid sales (**{100*heapM/vM:.0f}%**) report sales three years ago equal to exactly 90% of current sales; only {decM:.1f}% report any decline, versus {decK:.1f}% in Korea. The pattern is spread across 33 interviewers, all sectors and sizes, and looks like stylised round-number answers. Check R08b drops these firms.
2. **Unit/entry outliers in Korea.** {badK} Korean firms have a sales ratio above 5 or below 0.2 (up to ~10,500x); some written-out numbers in `d2x/n3x` confirm order-of-magnitude inconsistencies. Check R08a drops them.
3. **Survivor sample.** Firms with `l2 = -7` (not in business three years ago; 11 Morocco, 40 Korea) have no baseline and are excluded; WBES covers surviving firms only.
4. **Education item.** Korea's high-school share is at ceiling (mean 98%); Morocco's mean is 41%. It cannot serve as a comparable D3 outcome and the Adewumi & Zhang education index cannot be built.

## 3. Strategy and estimation
**Measurement decision (`04_MEASUREMENT_DECISION.md`): Strategy A, separate models.** Inclusive growth is formative; the indicators are nearly uncorrelated; weighting/sign choices change rankings (rank correlations 0.39-0.95); PCA is reported only as a dimensionality test.

**Models (pre-specified, `results/prespecification.json`):** for each outcome k, `IG_ki = a + b1 Product_i + b2 Process_i + b3 Website_i + g Controls_i + e_i`, estimated for Morocco (M1), Korea (M2), pooled with a Korea dummy (M3), and pooled with Product, Process and Website each interacted with Korea (M4). OLS for D1-D3, logit for D4 (average marginal effects reported). Controls: ln initial employment (growth models; ln current employment for levels), ln(1+age), foreign ownership (>=10%), exporter (>=10%), corporation, sector (manufacturing / retail / other services). Weights: `wstrict` rescaled to mean 1 within country; stratified Taylor-linearised variance (strata; no PSU variable exists; single-firm strata centred), t(n - strata) inference; estimators validated against statsmodels (`tests/test_svy.py`). **No 2SLS**: no credible instrument exists; Adewumi & Zhang's region-standardised R&D instrument cannot be rebuilt (only 45 Moroccan firms report a valid R&D amount). Estimation samples: Morocco N = {nrange('M1 Morocco')}, Korea N = {nrange('M2 Korea')}.

**Tiers.** Tier 1: the models above (Tables 5-9). Tier T2: pre-specified robustness checks R01-R12 and diagnostics (Table 10). Tier T3 (**exploratory**): sector and firm-size heterogeneity, e-filing as alternative digital proxy, Morocco-only education outcome. We tested 21 regressor-outcome associations per model; stars in the tables are unadjusted, Holm-adjusted p-values are provided in Table 9 and `Main_full`.

## 4. Results (associations, not causal effects)
Descriptives (Table 3): Moroccan firms report higher nominal growth than Korean firms (sales {T3.loc[0,'MAR mean']:.1f} vs {T3.loc[0,'KOR mean']:.1f} pp/yr; employment {T3.loc[2,'MAR mean']:.1f} vs {T3.loc[2,'KOR mean']:.1f} pp/yr), more product (13.2% vs 7.9%) and process innovation (6.7% vs 3.3%), more websites (63% vs 41%) and a higher low-skilled share among production workers (35% vs 19%). Female shares and energy-management adoption are similar (about 29-30% and 17%).

**D1 Economic growth (Table 5).** *Morocco:* no significant association of sales or productivity growth with product innovation ({cp('M1 Morocco','D1_sales','prod_innov')}), process innovation ({cp('M1 Morocco','D1_sales','proc_innov')}) or website ({cp('M1 Morocco','D1_sales','web')}); this is also true after excluding the heaped answers (R08b: {rb('R08b','M1 Morocco','D1_sales','prod_innov')}). *Korea:* process innovation is associated with lower sales growth ({cp('M2 Korea','D1_sales','proc_innov')} pp/yr; unweighted {rb('R01','M2 Korea','D1_sales','proc_innov')}) and with lower productivity growth; this sign is stable across all checks, but it does not survive Holm adjustment across 21 tests and rests on only 47 Korean process innovators. Product innovation is associated with higher sales growth in the weighted model ({cp('M2 Korea','D1_sales','prod_innov')}) but the unweighted estimate is {rb('R01','M2 Korea','D1_sales','prod_innov')} - the result depends on survey weights and is classed fragile. Website: {cp('M2 Korea','D1_sales','web')}, fragile.

**D2 Employment growth (Table 6).** No robust association in either country; Korean process innovation is weakly negative in the weighted model ({cp('M2 Korea','D2_emp','proc_innov')}) but vanishes unweighted ({rb('R01','M2 Korea','D2_emp','proc_innov')}). Consistent with Sime & Tadesse's point that jobs and productivity respond differently, nothing in our data shows innovation raising employment growth in either country.

**D3 Social composition (Table 7).** *Morocco:* process-innovating firms have a higher female employment share ({cp('M1 Morocco','D3_female','proc_innov',3)}, i.e. about 13.6 percentage points); this survives unweighted estimation, Holm adjustment and 95% of the specification/data checks (p_Holm = {g('M1 Morocco','D3_female','proc_innov','p_holm'):.3f}). Product innovation has a negative, fragile association ({cp('M1 Morocco','D3_female','prod_innov',3)}). *Korea:* product innovation is associated with a higher female share ({cp('M2 Korea','D3_female','prod_innov',3)}; unweighted {rb('R01','M2 Korea','D3_female','prod_innov',3)}); this is classed fragile because some specifications lose significance; the Morocco-Korea difference is large (p = {t9.loc[('Female share of permanent FT employees','Product innovation (h1)'),'p (diff)']:.3f}; Holm {t9.loc[('Female share of permanent FT employees','Product innovation (h1)'),'Holm p (M4 interaction, 21 tests)']:.3f}). These are shares at one date and say nothing about female employment growth. Low-skilled share: no robust association (Korea, website: {cp('M2 Korea','D3_lowskill','web',3)}, fragile).

**D4 Environmental practices (Table 8).** Website adopters are more likely to have adopted energy-management measures in Korea (log-odds {cp('M2 Korea','D4_energy','web',2)}; AME {100*g('M2 Korea','D4_energy','web','ame'):.1f} pp, p = {g('M2 Korea','D4_energy','web','ame_p'):.3f}; classed robust) but not robustly in Morocco (weighted AME {100*g('M1 Morocco','D4_energy','web','ame'):.1f} pp, yet negative when unweighted). In Morocco product innovators are more likely to monitor CO2 ({cp('M1 Morocco','D4_co2','prod_innov',2)} log-odds; unweighted significant; Holm p = {g('M1 Morocco','D4_co2','prod_innov','p_holm'):.3f}). The Moroccan process-innovation/CO2 coefficient ({g('M1 Morocco','D4_co2','proc_innov'):.1f}) is a **sparse-cell artefact** (1 of 39 process innovators monitors CO2; weighted cell nearly empty); the Firth bias-reduced estimate is {f_.coef_firth:.2f} (p = {f_.p_firth:.3f}). It must not be interpreted, and the Holm-significant country difference it produces (Table 9) is likewise unreliable. D4 outcomes are practice adoption, not environmental performance.

**Pooled models and country differences (Table 9, Figures 4-5).** In M3, process innovation is negatively and product innovation positively associated with sales growth, but M4 shows this is driven by Korea (joint Wald test of the three interactions: sales growth p = {t9.loc[('Sales growth (annualised log, pp)','Product innovation (h1)'),'Wald p all 3 interactions']:.3f}; female share p = {t9.loc[('Female share of permanent FT employees','Product innovation (h1)'),'Wald p all 3 interactions']:.3f}; low-skilled share p = {t9.loc[('Low-skilled share of production workers','Website (c22b)'),'Wald p all 3 interactions']:.3f}). Pooled common-slope estimates therefore should not be read as a shared Morocco-Korea relationship for those outcomes. After Holm correction, only the (unreliable) CO2 difference survives at 5%; the female-share/product-innovation difference has Holm p = 0.099.

## 5. Robustness and validation (Table 10; `06_robustness.py`)
Of the 42 country-outcome-regressor associations, **{cnt.get('Robust',0)} robust, {cnt.get('Fragile',0)} fragile, {cnt.get('Unreliable',0)} unreliable, {cnt.get('Null/imprecise',0)} null/imprecise** (robust = significant in baseline and unweighted runs and in at least 80% of checks with an unchanged sign). The main driver of fragility is the survey weights (Figure 6): several Korean associations shrink toward zero unweighted. Checks run: weighted vs unweighted, alternative weights, stratification ignored, winsorising at 1/99 (baseline), 5/95, none, trimming, alternative growth definitions (Adewumi & Zhang formula, CAGR, DHS arc), Korea/Morocco data-quality exclusions, minimal/extended controls, region FE, current size, ISIC sector, alternative foreign/exporter definitions, route-specific female share, low-skill definition, DK as category, fractional logit, Firth logit, influence (Cook's D; 73-98 influential Korean growth observations; effects remain signed but shrink), VIF (max {vifmax:.2f}), missing-data selection tests. *Missing data:* inclusion in the estimation sample is related to observables (selection-on-observables LR tests, Morocco p = {miss[miss.country=='MAR'].p_value.min():.3f}-{miss[miss.country=='MAR'].p_value.max():.3f}; Korea p = {miss[miss.country=='KOR'].p_value.min():.3f}-{miss[miss.country=='KOR'].p_value.max():.3f}), so complete-case results cannot be assumed representative of all firms (Korean selection is also detectable for growth outcomes); DK-as-category results (R11) are nearly identical to the baseline.
**Exploratory (T3):** heterogeneity tests with p<0.05 occur for {', '.join(sorted(set(f"{a.split(' ')[0]}:{b}:{c}" for a,b,c in sig_het)))}, mostly for the D4 outcomes where cells are sparse; they are not interpreted substantively. Replacing the website with e-tax filing (R10h) changes the digitalization coefficient substantially (e.g. Korea sales growth {rb('R10h','M2 Korea','D1_sales','web')}), showing that conclusions about "digitalization" depend on the proxy.

## 6. Methodological deviations from the source articles
1. **Role of innovation.** Phan treats innovation as an outcome of green practice; here it is an explanatory variable of inclusive-growth dimensions.
2. **No green index.** GEP (BMGc23a-j) and Adewumi & Zhang's GI score cannot be built; `ge8d`/`ge7` are single practice items. The equivalence of `ge8d` to BMGc23d is inferred from ordering, not verified.
3. **No IV/PSM/dose-response.** Adewumi & Zhang use 2SLS and Sime & Tadesse use PSM/dose-response; we have no credible instrument and a three-regressor selection-on-observables OLS/logit is not PSM. Our estimates are associations.
4. **Estimator and inference.** Phan clusters by country with country/year/industry FE (42 countries); with two countries this is infeasible, so we use a Korea dummy and survey-design linearised errors. WBES weights are used (Phan reports none).
5. **Outcome definitions.** Sales growth is annualised log growth (Adewumi & Zhang: (S_t - S_t-3)/S_t, reproduced in R07a); productivity is growth of sales per permanent FT employee (Sime & Tadesse: levels; not value added); employment growth replaces employment levels by category.
6. **Size.** Initial (3-year-ago) employment is the size control in growth models to avoid the mechanical size-growth link; Phan uses current ln(l1) (R09e). Age is ln(1+age).
7. **Education index.** Not reproducible (no university share).
8. **Sector.** Three harmonised groups instead of detailed industry FE (ISIC check R10a).
9. **Deflator.** Growth is nominal. A common country-level price index changes log growth by a constant within a country, hence only the Korea dummy/intercepts - not slopes - would change, *provided* fiscal-year timing is common; sector-specific inflation is not accounted for.

## 7. Limitations
Cross-sectional data and overlapping windows (innovation over the last 3 years, growth over the same 3 years) preclude temporal ordering; reverse causality and omitted firm quality are plausible. Small treated cells (47 Korean and 37 Moroccan process innovators in growth samples), heavy weight dispersion, DK-driven selection in Morocco, Moroccan sales heaping, Korean unit errors, nominal growth with different COVID-era windows, and weak proxies for digitalization and environmental practice limit inference. D3 cannot speak to inclusive employment growth and D4 cannot speak to environmental performance. Because 42 associations were examined, isolated significant coefficients should be treated as hypotheses.

## 8. Conclusion
The WBES 2023/2024 files support a defensible comparative analysis of **economic growth, employment growth, workforce composition and two environmental practices** in relation to innovation and a website proxy - but not a multidimensional Inclusive Growth Index. The data show no robust innovation or digitalization association with employment growth in either country, a stable negative Korean association between process innovation and sales/productivity growth that does not survive multiplicity correction, a robust Moroccan link between process innovation and female workforce share, and heterogeneity between countries concentrated in Korea. Future work needs panel or longitudinal WBES waves (female/skilled employment at two dates), the Green Economy module, richer ICT items and deflators.

## 9. Reproducibility
`python run_all.py` runs scripts 01-07 in order (about 3 minutes). Raw files in `data/raw/` are never modified; derived data in `data/processed/`; transformations and exclusions are logged in `logs/`; tests in `tests/`. See `README.md`.

## Appendix: output index
`01_ARTICLE_EXTRACTION.xlsx`, `01_ARTICLE_COMPARISON.md`, `02_*_DICTIONARY.xlsx`, `02_MISSING_DATA_REPORT.xlsx`, `03_VARIABLE_CROSSWALK.xlsx`, `04_INCLUSIVE_GROWTH_MEASUREMENT.xlsx`, `04_MEASUREMENT_DECISION.md`, `05_ECONOMETRIC_RESULTS.xlsx` (Tables 1-10 and full results), `06_FIGURES/` (F1 framework, F2/F2b distributions, F3 coefficient plot, F4 country comparison, F5 predictive margins, F6 weighting sensitivity).
"""
    open(os.path.join(OUT, "07_RESEARCH_REPORT.md"), "w").write(md)
    print("report written", len(md))

def diag_val(OUT, which):
    d = pd.read_excel(os.path.join(OUT, "04_INCLUSIVE_GROWTH_MEASUREMENT.xlsx"), sheet_name="Composite_diagnostics")
    r = d[d.country == "Pooled"].iloc[0]
    return f"{r.cronbach_alpha:.2f}" if which == "alpha" else f"{r.KMO:.2f}"
