import json
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
T=json.load(open('tables.json'))
doc=Document()
sec=doc.sections[0]; sec.left_margin=sec.right_margin=Cm(2.5); sec.top_margin=sec.bottom_margin=Cm(2.5)
st=doc.styles['Normal']; st.font.name='Times New Roman'; st.font.size=Pt(11.5)
st.element.rPr.rFonts.set(qn('w:eastAsia'),'Times New Roman')
st.paragraph_format.line_spacing=1.3; st.paragraph_format.space_after=Pt(6)
for n,sz in (('Heading 1',14),('Heading 2',12)):
    h=doc.styles[n]; h.font.name='Times New Roman'; h.font.size=Pt(sz); h.font.bold=True; h.font.color.rgb=RGBColor(0,0,0)
    h.element.rPr.rFonts.set(qn('w:eastAsia'),'Times New Roman'); h.paragraph_format.space_before=Pt(14); h.paragraph_format.space_after=Pt(6)
def P(t,b=False,i=False,al=None,sz=None):
    p=doc.add_paragraph(); r=p.add_run(t); r.bold=b; r.italic=i
    if sz: r.font.size=Pt(sz)
    if al=='c': p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    elif al!='l': p.alignment=WD_ALIGN_PARAGRAPH.JUSTIFY
    return p
def H1(t): doc.add_heading(t,1)
def H2(t): doc.add_heading(t,2)
def border(cell,**kw):
    tcPr=cell._tc.get_or_add_tcPr(); b=OxmlElement('w:tcBorders')
    for k,v in kw.items():
        e=OxmlElement(f'w:{k}'); e.set(qn('w:val'),'single'); e.set(qn('w:sz'),str(v)); e.set(qn('w:color'),'000000'); b.append(e)
    tcPr.append(b)
def table(title,head,rows,note,widths=None,fs=9):
    p=P(title,b=True,al='l'); p.paragraph_format.keep_with_next=True
    t=doc.add_table(rows=1+len(rows),cols=len(head)); t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for j,h in enumerate(head):
        c=t.rows[0].cells[j]; c.text=''; r=c.paragraphs[0].add_run(h); r.bold=True; r.font.size=Pt(fs)
        c.paragraphs[0].alignment=WD_ALIGN_PARAGRAPH.CENTER if j else WD_ALIGN_PARAGRAPH.LEFT; border(c,top=12,bottom=6)
    for i,row in enumerate(rows):
        for j,v in enumerate(row):
            c=t.rows[i+1].cells[j]; c.text=''; para=c.paragraphs[0]; para.paragraph_format.line_spacing=1.0; para.paragraph_format.space_after=Pt(1)
            r=para.add_run(str(v)); r.font.size=Pt(fs)
            para.alignment=WD_ALIGN_PARAGRAPH.CENTER if j else WD_ALIGN_PARAGRAPH.LEFT
            if i==len(rows)-1: border(c,bottom=12)
    if widths:
        for row in t.rows:
            for j,w in enumerate(widths): row.cells[j].width=Cm(w)
    q=P(note,i=True,al='l',sz=9); q.paragraph_format.space_before=Pt(3); q.paragraph_format.line_spacing=1.0
    doc.add_paragraph()
    return t

# ---------- Title page
P('Target Transparency, Target Horizon and Target Attainability in Manufacturing: Evidence from the World Bank Enterprise Surveys of Morocco (2023) and South Korea (2024)',b=True,al='c',sz=16)
P('[Author names and affiliations]',al='c',i=True)
P('Manuscript draft — prepared from the harmonised WBES Morocco 2023 × Korea 2024 database',al='c',i=True,sz=10)
H1('Abstract')
P('Management accounting research increasingly shows that how targets are communicated and how far ahead they look shape whether employees can actually reach them. Ai, Baloria, Sun and Wang (2024) document, across a global panel of manufacturers, that broader target transparency and longer target horizons are associated with targets that managers describe as harder to achieve. We test whether these associations travel to two contrasting institutional settings that were not part of their sample: Morocco (WBES 2023) and the Republic of Korea (WBES 2024). Using 773 manufacturing establishments that report production targets, and adopting their specifications (country×sector fixed effects, firm-level controls, heteroskedasticity-robust standard errors), we find that both transparency (−0.17 scale points per step, p<0.01) and horizon (−0.27, p<0.01) are negatively related to target attainability. The horizon result is statistically indistinguishable across countries; the transparency result is clear in Korea and imprecisely estimated in Morocco, although the cross-country difference is not significant. The horizon–attainability association is significantly stronger where promotion is based solely on performance (Δ = −0.25, p = 0.03), in line with a performance-evaluation channel, while evidence for planning- and “need-for-help” contingencies is weak or contrary to prediction. As an extension, we examine the innovation correlates of targets: establishments that set production targets are 6 to 17 percentage points more likely to report product innovation, process innovation or R&D, and harder targets are weakly associated with product/process innovation (+2.1 pp per scale point, p<0.10). The results are cross-sectional and perceptual; we discuss identification limits and what they imply for the external validity of the original findings.',sz=11)
P('Keywords: target setting; management control systems; target transparency; target horizon; innovation; World Bank Enterprise Surveys; Morocco; South Korea',i=True,al='l',sz=10.5)
P('JEL: M41, M52, O31, L60, O53',i=True,al='l',sz=10.5)

H1('1. Introduction')
P('Targets are the most common instrument through which organisations translate strategy into operational expectations. Whether a target motivates or demoralises depends on its difficulty (Locke & Latham, 2002), on who knows about it, on how long the organisation is given to reach it, and on how it is tied to evaluation and rewards (Merchant & Van der Stede, 2017). A large body of work in management accounting has studied these design choices in single-country or single-industry settings, but systematic cross-country evidence on how target design is related to target attainability remains scarce, in part because comparable firm-level data on internal control practices are rare.')
P('The World Bank Enterprise Surveys (WBES) Manufacturing Module is one of the few harmonised sources that ask plant-level respondents about production targets: whether targets exist, how long their horizon is, who is aware of them, how easy they are to achieve, and how bonuses and promotions are determined. Ai, Baloria, Sun and Wang (2024) exploit this module for 2017–2022 and report that greater target transparency and longer target horizons are associated with targets that are harder to achieve, with the associations concentrated where targets are used for performance evaluation, where worker-retention concerns are strong, and where operational planning is more likely.')
P('This paper asks whether those regularities hold in two economies that differ sharply in their institutional environment but both completed the module after the original sample window: Morocco (survey year 2023), a middle-income North African economy with a large informal sector, and the Republic of Korea (survey year 2024), a high-income economy with a long tradition of formal management systems and group-based corporate governance. The two settings give us unusually strong variation in the conditions that the original paper treats as moderators — formality of competition, financing access, performance-based promotion, reliability of electricity — and thereby a meaningful test of external validity.')
P('We make three contributions. First, we provide an out-of-sample replication of the Ai et al. (2024) baseline equations for two countries not in their sample. Second, we test their contingency predictions (performance evaluation, planning, need for help, environmental uncertainty) using the variables the new waves allow us to construct, and we document which cannot be tested. Third, we extend the analysis to innovation: because the same survey records product innovation, process innovation and R&D spending, we can ask whether establishments with harder targets, or with particular target designs, are more innovative — a question that connects the target-setting literature to the debate on control systems and innovation (Simons, 1995; Bisbe & Otley, 2004; Davila, 2000).')
P('Our main findings are as follows. The negative associations of transparency and horizon with attainability replicate in the pooled sample and are robust to weights, ordered-logit estimation and the omission of controls. The horizon association is almost identical in Morocco and Korea; the transparency association is clearly negative only in Korea, but we cannot reject equality across countries. Only the performance-evaluation contingency is supported statistically. Finally, target-setting establishments are markedly more innovative than those without targets, but conditional on having targets, the design features add little additional explanatory power for innovation.')

H1('2. Conceptual background and hypotheses')
H2('2.1 Target transparency')
P('Making targets visible to a wider group of employees can create shared goals and coordination (Merchant & Van der Stede, 2017), but it also raises the stakes of failure, invites comparison and reduces managers’ ability to adjust targets quietly. When more people are aware of a target, managers have fewer degrees of freedom to set “sandbagged” goals, and broadly communicated targets are likely to be set closer to the true capacity of the plant or even above it. If respondents interpret “easy to achieve” relative to what the workforce believes is expected, wide awareness should be associated with targets perceived as harder. Following Ai et al. (2024):')
P('H1: Target transparency is negatively associated with target attainability.',i=True)
H2('2.2 Target horizon')
P('Long-horizon targets are, by construction, further from the realisation of outcomes and subject to more uncertainty about demand, inputs and technology. They also provide fewer feedback points and allow slack to build up, which suggests that managers will describe them as less certain to be reached (Locke & Latham, 2002). On the other hand, long horizons may permit the investments in capacity and capability that make targets feasible. Maintaining the original prediction:')
P('H2: Target horizon is negatively associated with target attainability.',i=True)
H2('2.3 Contingencies')
P('Ai et al. (2024) argue that the associations should be stronger when targets matter for consequences. We examine four contingency tests the data allow: (H3a) performance evaluation — promotion of non-managers based solely on performance and ability; (H3c) operational planning — capacity utilisation at or above 80 percent; (H4a) need for help — managers’ bonuses based on own or team performance rather than establishment performance; and (H4b) environmental uncertainty — electricity reported as a major or very severe obstacle. H3b (worker retention) requires national unemployment time series external to the WBES and is not testable with the supplied database.')
H2('2.4 Targets and innovation (extension)')
P('The literature on control systems and innovation offers opposing arguments. Tight, difficult targets can focus attention and generate the pressure that triggers problem-solving search (Simons, 1995; Bisbe & Otley, 2004), but they can also crowd out exploratory activity and reward short-term compliance (Davila, 2000; Ahrens & Chapman, 2004). We therefore treat innovation outcomes as an exploratory extension and formulate a directional but modest expectation:')
P('H5: Establishments with harder-to-achieve targets report more innovation (product, process, R&D).',i=True)

H1('3. Data and method')
H2('3.1 Data')
P('The data are the WBES Morocco 2023 and Korea 2024 files, harmonised into a single database of 2,116 establishments (598 in Morocco, 1,518 in Korea) with 315 common variables. The Manufacturing Module is applied to manufacturing establishments only, which yields 411 Moroccan and 836 Korean establishments with module information. Production targets exist in 55.0% of Moroccan and 65.7% of Korean manufacturing establishments answering the question. For those that have targets, the horizon (r5), the degree of awareness (r7) and the difficulty of achievement (r6) are recorded, giving 226 (Morocco) and 547 (Korea) establishments with non-missing target-achievement values. Missing-value codes (−9 “don’t know”, −7 “does not apply”, −6) are recoded to missing.')
H2('3.2 Variables')
P('Following Ai et al. (2024), Target_Achievement is the response to “How easy or difficult was it to achieve production targets overall?” (six-point scale) multiplied by −1, so that more negative values indicate less attainable targets. Target_Transparency (r7) is coded 1–4 from “only senior managers” to “all managers and most production workers”. Target_Horizon (r5) is coded 1–3 from short-term to long-term focus. Firm controls: size (ln of permanent full-time employees), age (ln of years since start of operations), manager experience in the sector, publicly listed, foreign-owned (≥10% foreign ownership), part of a larger firm, existing loan or credit line, internationally recognised quality certification, competition from informal firms, power outages, exporter status, and labour productivity (ln sales per employee, standardised within country because the two samples are in different currencies). Continuous controls are winsorised at the 1st and 99th percentiles within country. The innovation outcomes are three indicators: product/service innovation in the last three years (h1), process innovation (h5) and R&D spending in the last fiscal year (h8).')
H2('3.3 Estimation')
P('Our baseline is the linear specification of Equations (1) and (2) in Ai et al. (2024):')
P('TargetAchievement_i = α·Transparency_i  (or β·Horizon_i) + γ′Firm_i + δ_{c,s} + ε_i,',i=True,al='c')
P('where δ_{c,s} are country×sector fixed effects (sector coding differs by country, so we interact). Year fixed effects are collinear with country in this two-wave design and are absorbed. Two departures from the original are unavoidable. First, with only two countries we cannot cluster standard errors by country; we use heteroskedasticity-robust (HC3) standard errors, which are appropriate for the small samples. Second, country-level macro controls (GDP, inflation, institutions) are not separately identified from the country fixed effects and are omitted. Robustness checks include ordered logit, estimation without controls, country fixed effects only, survey weights (strict eligibility weights), and an explicit country interaction. Innovation outcomes are modelled with logit and reported as average marginal effects. All analyses are reproducible from the supplied workbook.')
H2('3.4 Coding assumptions and limitations of the data')
P('Three coding decisions merit disclosure. (i) The supplied workbook does not contain value labels; the codings of r5, r7 and r10 follow the table in the “Ai2024_Target_Setting” sheet, while the coding of r9 (1–2 = individual or team basis; 3–4 = establishment or other) follows the standard WBES questionnaire and should be verified against the codebook before submission. (ii) Capacity utilisation (f1) is missing for most Moroccan establishments, so the planning split is dominated by Korea (N = 129 in Morocco versus 537 in Korea). (iii) A small number of Moroccan establishments report implausible start years and are treated as missing for the age control.')

H1('4. Results')
H2('4.1 Descriptive evidence')
P('Table 1 compares the two samples. Targets in Korea are perceived as markedly harder: 29.6% of Korean respondents rate their targets as difficult or very difficult (scores 5–6), against 6.7% in Morocco, and the mean achievement score is −3.94 versus −3.04 (p<0.001). By contrast, transparency (2.64 vs 2.52) and horizon (2.05 vs 2.11) do not differ significantly across countries. The institutional contrast is visible in the controls: Moroccan establishments are far more likely to compete with informal firms (57% vs 7%), less likely to have a loan (27% vs 60%) or a quality certification (22% vs 51%), and more likely to promote non-managers solely on performance (65% vs 29%).')
table('Table 1. Descriptive statistics by country (manufacturing establishments)',['Variable','Morocco\nN','Morocco\nMean','Korea\nN','Korea\nMean','p (Welch)'],T['t1'],'Notes: Manufacturing Module sample. p-values from Welch t-tests of equality of means. Target achievement = −1 × difficulty (1–6).',[6.2,1.8,1.8,1.8,1.8,2.2])
H2('4.2 Baseline results')
P('Table 2 reports the baseline estimates. In the pooled sample, a one-step increase in transparency is associated with a 0.21-point decrease in target achievement when entered alone (column 1) and 0.17 points when horizon is included (column 3). A one-step increase in horizon is associated with a 0.31-point decrease alone (column 2) and 0.27 points jointly. With a pooled standard deviation of target achievement of about 1.25 points, moving from the lowest to the highest transparency category (three steps) corresponds to about 0.4 standard deviations, and moving from short-term to long-term horizon (two steps) to about 0.45 standard deviations. H1 and H2 are therefore supported in the pooled data. Figure 1 plots the estimates by country.')
P('The horizon coefficient is virtually identical in Morocco (−0.30, p<0.01) and Korea (−0.27, p<0.01). The transparency coefficient is −0.16 in Korea (p<0.01) but only −0.06 in Morocco (p = 0.50). This difference should not be over-interpreted: the Moroccan subsample has 149 usable observations, and in a pooled model with country interactions the Korea×Transparency term is small and imprecise (0.02, p = 0.87), so we cannot reject that the transparency relationship is the same in both countries. We conclude that H2 is supported in both settings, whereas support for H1 is demonstrated for Korea and for the pooled sample but is inconclusive for Morocco alone.')
table('Table 2. Target transparency, target horizon and target achievement',T['t2']['head'],T['t2']['rows'],'Notes: OLS. Dependent variable: Target_Achievement (−1 × difficulty; more negative = harder). Heteroskedasticity-robust (HC3) standard errors in parentheses. Country×sector fixed effects. *p<0.10, **p<0.05, ***p<0.01.',[4.6,2.3,2.3,2.3,2.3,2.3],fs=8.5)
doc.add_picture('fig1.png',width=Cm(14)); doc.paragraphs[-1].alignment=WD_ALIGN_PARAGRAPH.CENTER
P('Figure 1. Estimated association of transparency and horizon with target achievement, by sample. Points are coefficients from the specification in Table 2 (column 3 for pooled, columns 4–5 for countries); bars are 95% confidence intervals.',i=True,al='l',sz=9)
H2('4.3 Contingencies')
P('Table 3 reports the sub-sample tests. The performance-evaluation split gives the clearest result: the horizon coefficient is −0.51 where promotion rests solely on performance and ability, against −0.28 elsewhere, and the interaction is significant (−0.25, p = 0.03). For transparency the same pattern is visible in sign (−0.28 vs −0.23) but the difference is not significant. We interpret this as partial support for H3a.')
P('The planning split (capacity utilisation ≥ 80%) does not support H3c: both transparency and horizon relationships are, if anything, steeper in low-utilisation establishments, though the low-utilisation group is small (88–90 observations) and the interactions are insignificant. The need-for-help split is also not supportive: coefficients are not larger where bonuses are based on own or team performance. For environmental uncertainty, the horizon coefficient is larger where electricity is a major obstacle (−0.36 vs −0.25) with a marginally significant interaction (−0.27, p = 0.06), consistent with H4b for horizon; for transparency the sign is reversed (+0.02 vs −0.19), which does not match the prediction. Given the number of splits, the multiple-testing problem, and the limited sample sizes, we regard only the performance-evaluation result as informative.')
table('Table 3. Contingency analyses',['Contingency (split variable = 1 vs 0)','Transparency\nsplit = 1','Transparency\nsplit = 0','Transparency\ninteraction','Horizon\nsplit = 1','Horizon\nsplit = 0','Horizon\ninteraction'],T['t3'],'Notes: Each cell is from a separate OLS regression with the full set of firm controls and country×sector fixed effects, HC3 standard errors in parentheses. “Interaction” = coefficient on (variable × split dummy) in the pooled model. Splits: performance evaluation = promotion based solely on performance; planning = capacity utilisation ≥80%; need for help = managers’ bonus based on own/team performance; environmental uncertainty = electricity a major/very severe obstacle. *p<0.10, **p<0.05, ***p<0.01.',[4.0,2.1,2.1,2.0,2.1,2.1,2.0],fs=8)
H2('4.4 Robustness')
P('Table 4 shows that the pooled results are stable. Excluding firm controls, using only country fixed effects, or weighting by the WBES strict-eligibility weights leaves both coefficients negative and significant (weighting increases the magnitudes to −0.19 and −0.32). The ordered-logit estimates are also negative at p<0.01. Country interactions confirm that the cross-country differences are small relative to their standard errors.')
table('Table 4. Robustness of the baseline results',['Specification','Transparency','Horizon','N'],T['t4'],'Notes: HC3 standard errors in parentheses (ordered logit: conventional). Dependent variable: Target_Achievement. The last two rows report main effects (for Morocco) and the interaction terms in a model with Korea interactions. *p<0.10, **p<0.05, ***p<0.01.',[7.4,3.0,3.0,1.8],fs=9)
H2('4.5 Extension: targets and innovation')
P('Table 5 reports average marginal effects from logit models for innovation. Conditional on having a target, harder targets are positively but weakly related to innovation: each additional step of difficulty is associated with 2.1 percentage points higher probability of product or process innovation (p<0.10) and with smaller, insignificant effects for the separate outcomes (product +1.6 pp, process +0.4 pp, R&D +0.9 pp). Longer horizons are associated with higher process innovation (+2.5 pp, p<0.10), and broader transparency with lower R&D spending (−4.6 pp, p<0.01). These patterns are consistent with H5 only weakly, and the transparency–R&D association hints that wide dissemination of operational targets coincides with less exploratory investment, a conjecture that deserves dedicated testing.')
P('A much sharper pattern appears at the extensive margin: having production targets at all is associated with a 13.9 pp higher probability of product innovation, 5.8 pp for process innovation and 16.8 pp for R&D (all p<0.01; Table 5, lower panel). Because setting targets is itself a marker of formal management practice (Bloom & Van Reenen, 2007), this should be read as a correlation between structured management and innovative activity rather than as an effect of targets per se.')
table('Table 5. Target design and innovation (average marginal effects, logit)',['Outcome','Difficulty\n(1–6)','Transparency','Horizon','N','Mean of Y'],T['t5'],'Notes: Logit, average marginal effects with HC1 standard errors in parentheses; firm controls and country×sector fixed effects included. Difficulty = −1 × Target_Achievement. *p<0.10, **p<0.05, ***p<0.01.',[4.6,2.1,2.3,2.1,1.6,2.0],fs=9)
table('Table 5b. Having production targets and innovation',['Outcome','AME of having targets','p-value','N'],[[r[0],r[1],r[2],str(r[3])] for r in T['ht']],'Notes: Logit AME, manufacturing establishments answering the target question; same controls and fixed effects as Table 5.',[4.6,4.0,2.4,2.0],fs=9)

H1('5. Discussion')
P('Three conclusions emerge. First, the core Ai et al. (2024) regularity travels: in two economies outside their sample, establishments that disseminate targets broadly or set them over longer horizons describe those targets as harder to achieve. The magnitude is substantial — about 0.4 standard deviations for the contrasts between the extreme categories — and it is robust to specification choices. Because the horizon coefficient is almost identical in Morocco and Korea despite their different institutional environments, the relationship appears to reflect something general about how targets work rather than a quirk of a specific economy.')
P('Second, the contingency evidence is thin. Only the performance-evaluation interaction for horizon is statistically supported. The failure of the planning and need-for-help splits to behave as predicted may reflect measurement (capacity utilisation is largely missing for Morocco; the bonus-basis variable is coded from a standard questionnaire), power (small subsamples), or the possibility that the mechanisms operate differently in less formal economies. We cannot distinguish among these explanations with the present data.')
P('Third, the innovation extension suggests that the mere presence of targets is a marker of an innovation-active organisation, whereas variation in target design within target-setting establishments has modest predictive power. Practitioners should be cautious about reading “harder targets” as a lever for innovation: the estimated effect is small and borderline.')
H2('Limitations')
P('The evidence is cross-sectional and based on a single respondent’s perception of target difficulty, so it is subject to reverse causality (managers who have achieved their targets may remember them as easier), common-method bias and selection into target setting. The perception of “difficulty” is not benchmarked to an objective measure of performance. With two countries, we cannot use country-clustered inference and cannot separate the effects of country-level institutions from other country-specific factors; our evidence on external validity is therefore suggestive. The two surveys were fielded in different years (2023 and 2024) and use independent sampling frames. Listwise deletion reduces the analytic sample from 773 to 671 establishments (149 in Morocco), which constrains power for Morocco-specific and contingency analyses. The H3b retention contingency, the Need-for-Help coding, and the planning variable all depend on assumptions or external data described in Section 3.4.')

H1('6. Conclusion')
P('This paper provides out-of-sample evidence from Morocco and Korea that supports the central claim of Ai et al. (2024): transparent and long-horizon targets are associated with targets that managers perceive as harder to achieve. The horizon result holds in both countries; the transparency result is clearest in Korea. The performance-evaluation channel receives partial support; the other contingencies do not. Establishments that set targets are substantially more innovative than those that do not, but within target-setting establishments, target design explains little of the variation in innovation. Future work should exploit panel structure (repeat WBES waves), objective performance measures and a larger set of countries to establish whether target design causally shapes attainability and innovation.')

H1('References')
refs=['Ahrens, T., & Chapman, C. S. (2004). Accounting for flexibility and efficiency: A field study of management control systems in a restaurant chain. Contemporary Accounting Research, 21(2), 271–301.',
'Ai, X., Baloria, V. P., Sun, H., & Wang, M. (2024). Target setting: Global evidence. Working paper (December 2024).',
'Bisbe, J., & Otley, D. (2004). The effects of the interactive use of management control systems on product innovation. Accounting, Organizations and Society, 29(8), 709–737.',
'Bloom, N., & Van Reenen, J. (2007). Measuring and explaining management practices across firms and countries. Quarterly Journal of Economics, 122(4), 1351–1408.',
'Davila, T. (2000). An empirical study on the drivers of management control systems’ design in new product development. Accounting, Organizations and Society, 25(4–5), 383–409.',
'Locke, E. A., & Latham, G. P. (2002). Building a practically useful theory of goal setting and task motivation: A 35-year odyssey. American Psychologist, 57(9), 705–717.',
'Merchant, K. A., & Van der Stede, W. A. (2017). Management Control Systems: Performance Measurement, Evaluation and Incentives (4th ed.). Pearson.',
'Simons, R. (1995). Levers of Control: How Managers Use Innovative Control Systems to Drive Strategic Renewal. Harvard Business School Press.',
'World Bank (2023, 2024). Enterprise Surveys: Morocco 2023; Republic of Korea 2024. Manufacturing Module. The World Bank, Washington, DC.']
for r in refs:
    p=P(r,al='l',sz=10.5); p.paragraph_format.left_indent=Cm(1); p.paragraph_format.first_line_indent=Cm(-1)
doc.save('/home/user/01/Target_Setting_Morocco_Korea_manuscript.docx')
print('saved')
